-- Create table products
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price decimal(10, 2) not null,
  image_url text,
  category text,
  stock_quantity integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Bật Row Level Security (RLS)
alter table products enable row level security;

-- Cho phép tất cả mọi người đọc sản phẩm
create policy "Allow public read access" on products
  for select using (true);
